heroku:
  stage: deploy
  only:
    - master
  script:
    - git config --global user.email "narasimha.nandikonda.17.1@mountblue.tech"
    - git config --global user.name "NarasimhaMount"
    - rm -rf .git
    - git init
    - git add .
    - git commit -m "initial commit"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/blogtopost.git
    - git push -f heroku master