heroku:
  stage: deploy
  only:
    - master
  script:
    - git config --global user.email "narasimha.nandikonda.17.1@mountblue.tech"
    - git config --global user.name "NarasimhaMount"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/blogtopost.git
    - git push -u heroku master
