heroku:
  stage: deploy
  only:
    - master
  script:
    - git config --global user.email "narasimha.nandikonda.17.1@mountblue.tech"
    - git config --global user.name "NarasimhaMount"
    - git push -u heroku master
